# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f9579443baa6d9989a91a304eca57aa595ff88197f7513e4277b5198f4ea1cde97844f4d792b0a08a0e869dc6a7a2f784b465513aff4a43dee41d9c6743d50

test:
  secret_key_base: a9d7e898293d81df182928e081f8ccbe5ef38a93e768032ea775cbc10b024b52bf627cc663cf6d5571c6c9ff25bc2ff52898a5f5508b337fdbb9fdcf3c875913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
